baseurl = "https://wnharu.com/"
title = "wnharu's blog"
theme = "hugo_theme_robust"

googleAnalytics = "UA-130631884-1"
disqusShortname = "XYW"

[blackfriday]
  extensions = ["hardLineBreak"]

[params]
  # description = "This is site description"
  dateformat = "Jan 2, 2006"
  googlefonts = "https://fonts.googleapis.com/css?family=Lobster|Lato:400,700"
  fontfamily = "Lato,YuGothic,'Hiragino Kaku Gothic Pro',Meiryo,sans-serif"
  logofontfamily = "Lobster, cursive"

[params.author]
  thumbnail = "images/author.jpg"
  name = "wnharu"
  description = "<p>フリーランスエンジニアです！！</p>"
  # facebook = "https://www.facebook.com/wnharu"
  twitter = "https://twitter.com/wnharu"
  github = "https://github.com/wnharu"

[outputs]
page = [ "HTML", "AMP" ]

