version: 2

references:

jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.52
    working_directory: ~/hugo
    # need staging environment
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
      HUGO_ENV: production 
    steps:
      - run: apk update && apk add git
      - checkout
      - run: git submodule sync && git submodule update --init
      - run: hugo -v -d $HUGO_BUILD_DIR

  deploy:
    docker:
      - image: cibuilds/aws:1.16.43
    steps:
      - attach_workspace:
          at: ./generated-site
      - run:
          name: Deploy to S3 if tests pass and branch is Master
          command: aws s3 sync generated-site/docs s3://circle-production-static-site/docs/ --delete
 
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
