version: 2

references:

jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.52
    working_directory: ~/hugo
    # need staging environment
    environment:
      HUGO_ENV: production 
    steps:
      - run: apk update && apk add git
      - checkout
      - run: git submodule sync && git submodule update --init
      - run: hugo -v
      - persist_to_workspace:
          root: ~/hugo
          paths:
            - public

  deploy:
    docker:
      - image: cibuilds/aws:1.16.43
    working_directory: ~/hugo/public
    steps:
      - attach_workspace:
          at: ~/hugo/public
      - run:
          name: Deploy to S3 if tests pass and branch is Master
          command: aws s3 sync public s3://wnharu.com/ --delete
      - run:
          name: Distribution to cloudfront
          command: aws cloudfront create-invalidation --distribution-id EGN8TQM0WECN --paths '/*'

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
